services:
  data-collector:
    build: src/data-collector
    environment:
      GCS_BUCKET_NAME: # define in .env
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/ml-workflow
    secrets:
      - ml-workflow
    volumes:
      - ./src/data-collector:/app
      - persistent:/persistent:rw

  data-processor:
    build: src/data-processor
    environment:
      GCS_BUCKET_NAME: # define in .env
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/ml-workflow
    secrets:
      - ml-workflow
    volumes:
      - ./src/data-processor:/app
      - persistent:/persistent:rw

  model-training-local:
    build: src/model-training
    entrypoint: python3 -m package.trainer.task --bucket_name=${GCS_BUCKET_NAME}
    environment:
      GCS_BUCKET_NAME: # defined in .env
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/ml-workflow
    secrets:
      - ml-workflow
    volumes:
      - ./src/model-training:/app
      - persistent:/persistent:rw

# remote, using Vertex AI
  model-training:
    build: src/model-training
    environment:
      GCS_BUCKET_NAME: # defined in .env
      GCS_PACKAGE_URI: # defined in .env
      GCP_PROJECT: # defined in .env
      GCP_REGION: # defined in .env
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/ml-workflow
    secrets:
      - ml-workflow
    volumes:
      - ./src/model-training:/app

secrets:
  ml-workflow:
    file: ../secrets/ml-workflow.json
    
volumes:
  persistent: